# !/usr/bin/python
# -*- coding: utf-8 -*-
from django import forms

class SelectionForm(forms.Form):
    projectName = forms.CharField(required=False, max_length=30)
    projectNumber = forms.CharField(required=False, max_length=30)
    projectLocation = forms.CharField(required=False, max_length=30)
    projectAltitude = forms.FloatField(required=False, min_value=0)
    projectInletPressure = forms.FloatField(required=True, min_value=0)
    projectFrequency = forms.FloatField(required=True, min_value=0)
    projectMachNums = forms.FloatField(required=False, min_value=1)
    machVolt = forms.FloatField(required=False, min_value=0)
    securityCoeff = forms.FloatField(required=True, min_value=0)
    eiRating = forms.FloatField(required=True, min_value=0)
    ambTemp = forms.FloatField(required=True, min_value=0)
    ratedFlow = forms.FloatField(required=True, min_value=0)
    ratedPressure = forms.FloatField(required=True, min_value=0, max_value=3)
    ratedTemp = forms.FloatField(required=True, min_value=0, max_value=100)
    ratedHumidity = forms.FloatField(required=True, min_value=0, max_value=100)
    rpPressure = forms.FloatField(required=True, min_value=0, max_value=2)
    rpInletLoss = forms.FloatField(required=True, min_value=0, max_value=1)
    rpOutLetLoss = forms.FloatField(required=True, min_value=0, max_value=1)
    rpOutletPressure = forms.FloatField(required=True, min_value=0, max_value=1)
    rpInletTemp = forms.FloatField(required=True, min_value=0, max_value=100)
    rpInletHumidity = forms.FloatField(required=True, min_value=0, max_value=100)
    dp1Pressure = forms.FloatField(required=True, min_value=0, max_value=2)
    dp1InletTemp = forms.FloatField(required=True, min_value=0, max_value=100)
    dp1InletHumidity = forms.FloatField(required=True, min_value=0, max_value=100)
    dp1p1flow = forms.FloatField(required=True, min_value=0, max_value=1)
    dp1p1Pressure = forms.FloatField(required=True, min_value=0, max_value=2)
    dp1p2flow = forms.FloatField(required=True, min_value=0, max_value=1)
    dp1p2Pressure = forms.FloatField(required=True, min_value=0, max_value=2)
    dp1p3flow = forms.FloatField(required=True, min_value=0, max_value=1)
    dp1p3Pressure = forms.FloatField(required=True, min_value=0, max_value=2)
    dp1p4flow = forms.FloatField(required=True, min_value=0, max_value=1)
    dp1p4Pressure = forms.FloatField(required=True, min_value=0, max_value=2)
    dp1p5flow = forms.FloatField(required=True, min_value=0, max_value=1)
    dp1p5Pressure = forms.FloatField(required=True, min_value=0, max_value=2)
    dp1p6flow = forms.FloatField(required=True, min_value=0, max_value=1)
    dp1p6Pressure = forms.FloatField(required=True, min_value=0, max_value=2)
    dp2Pressure = forms.FloatField(required=True, min_value=0, max_value=2)
    dp2InletTemp = forms.FloatField(required=True, min_value=0, max_value=100)
    dp2InletHumidity = forms.FloatField(required=True, min_value=0, max_value=100)
    dp2p1flow = forms.FloatField(required=True, min_value=0, max_value=1)
    dp2p1Pressure = forms.FloatField(required=True, min_value=0, max_value=2)
    dp2p2flow = forms.FloatField(required=True, min_value=0, max_value=1)
    dp2p2Pressure = forms.FloatField(required=True, min_value=0, max_value=2)
    dp2p3flow = forms.FloatField(required=True, min_value=0, max_value=1)
    dp2p3Pressure = forms.FloatField(required=True, min_value=0, max_value=2)
    dp2p4flow = forms.FloatField(required=True, min_value=0, max_value=1)
    dp2p4Pressure = forms.FloatField(required=True, min_value=0, max_value=2)
    dp2p5flow = forms.FloatField(required=True, min_value=0, max_value=1)
    dp2p5Pressure = forms.FloatField(required=True, min_value=0, max_value=2)
    dp2p6flow = forms.FloatField(required=True, min_value=0, max_value=1)
    dp2p6Pressure = forms.FloatField(required=True, min_value=0, max_value=2)
    dp3Pressure = forms.FloatField(required=True, min_value=0, max_value=2)
    dp3InletTemp = forms.FloatField(required=True, min_value=0, max_value=100)
    dp3InletHumidity = forms.FloatField(required=True, min_value=0, max_value=100)
    dp3p1flow = forms.FloatField(required=True, min_value=0, max_value=1)
    dp3p1Pressure = forms.FloatField(required=True, min_value=0, max_value=2)
    dp3p2flow = forms.FloatField(required=True, min_value=0, max_value=1)
    dp3p2Pressure = forms.FloatField(required=True, min_value=0, max_value=2)
    dp3p3flow = forms.FloatField(required=True, min_value=0, max_value=1)
    dp3p3Pressure = forms.FloatField(required=True, min_value=0, max_value=2)
    dp3p4flow = forms.FloatField(required=True, min_value=0, max_value=1)
    dp3p4Pressure = forms.FloatField(required=True, min_value=0, max_value=2)
    dp3p5flow = forms.FloatField(required=True, min_value=0, max_value=1)
    dp3p5Pressure = forms.FloatField(required=True, min_value=0, max_value=2)
    dp3p6flow = forms.FloatField(required=True, min_value=0, max_value=1)
    dp3p6Pressure = forms.FloatField(required=True, min_value=0, max_value=2)