# Generated by Django 2.1.7 on 2019-04-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selectedturbo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testpoints',
            options={'verbose_name': '工况点', 'verbose_name_plural': '工况点'},
        ),
        migrations.AlterModelOptions(
            name='turbo',
            options={'verbose_name': '鼓风机', 'verbose_name_plural': '鼓风机'},
        ),
    ]
