# Generated by Django 2.1.7 on 2019-09-23 09:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('selectedturbo', '0003_auto_20190429_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='', max_length=100, verbose_name='项目名称')),
                ('project_index', models.CharField(default='', max_length=100, verbose_name='项目编号')),
                ('project_address', models.CharField(default='', max_length=100, verbose_name='项目地址')),
                ('project_engineer', models.CharField(default='', max_length=100, verbose_name='项目工程师')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
                ('is_imperial', models.BooleanField(default=False)),
                ('altitude', models.FloatField(default=0)),
                ('inlet_press', models.FloatField(default=0)),
                ('frequency_select', models.CharField(choices=[('50', '50HZ'), ('60', '60HZ')], default='50', max_length=100)),
                ('units_num', models.IntegerField(default=1)),
                ('volt', models.IntegerField(default=400)),
                ('material', models.CharField(default='ALU', max_length=30)),
                ('safety_factor', models.FloatField(default=1)),
                ('ei_rating', models.FloatField(default=3)),
                ('env_temp', models.FloatField(default=0)),
                ('rating_flow', models.FloatField(default=0)),
                ('rating_pressure', models.FloatField(default=0)),
                ('rating_temp', models.FloatField(default=0)),
                ('rating_humi', models.FloatField(default=0)),
                ('rating_point_inlet_pressure', models.FloatField(default=0)),
                ('rating_point_inlet_temp', models.FloatField(default=0)),
                ('rating_point_humi', models.FloatField(default=0)),
                ('rating_point_inlet_loss', models.FloatField(default=0)),
                ('rating_point_outlet_loss', models.FloatField(default=0)),
                ('rating_point_out_pressure', models.FloatField(default=0)),
                ('max_flow_coeff', models.FloatField(default=0)),
                ('max_pressure_coeff', models.FloatField(default=0)),
                ('working_conditions', models.TextField(default='')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selectedturbo.Project')),
            ],
        ),
    ]
